// Code generated by go doublegen; DO NOT EDIT.
// This file was generated at 2020-02-09T23:30:54+11:00

// Package examples provides a TestDouble implementation of examples.API
package examples

import "github.com/lwoggardner/godouble/godouble"

type APIDouble struct {
	API
	*godouble.TestDouble
}

func NewAPIDouble(t godouble.T, configurators ...func(*godouble.TestDouble)) *APIDouble {
	result := &APIDouble{}
	result.TestDouble = godouble.NewDouble(t, (*API)(nil), configurators...)
	return result
}

func (d *APIDouble) QueryWithOptions(i0 int, i1 ...string) (r0 *Results) {
	returns := d.TestDouble.Invoke("QueryWithOptions", i0, i1)
	r0, _ = returns[0].(*Results)
	return
}

func (d *APIDouble) SomeCommand() {
	d.TestDouble.Invoke("SomeCommand")

}

func (d *APIDouble) SomeQuery(i0 string) (r0 Results, r1 error) {
	returns := d.TestDouble.Invoke("SomeQuery", i0)
	r0, _ = returns[0].(Results)
	r1, _ = returns[1].(error)
	return
}

func (d *APIDouble) local(i0 exampleint) (r0 exampleint) {
	returns := d.TestDouble.Invoke("local", i0)
	r0, _ = returns[0].(exampleint)
	return
}
